version: "2"

# When filling out the manifest.yaml, please follow these instructions:
# 1. Replace all ALL_CAPS_TEMPLATES with the appropriate values for your connector.
# 2. Name the <VARIABLES> and make sure the references match.
# 3. Keep all lower case variables as they are.

name: %PRETTY_NAME%
description: %PRETTY_NAME%

service_account:
  display_name: %PRETTY_NAME% Bot

functions:
  - name: extraction
    description: Extraction function for %PRETTY_NAME%
  - name: loading
    description: Loading function for $PRETTY_NAME%
  - name: install_initial_domain_mapping
    description: Create blueprint and install initial domain mapping

keyring_types:
  - id: pat-connection
    name: %PRETTY_NAME% Connection
    description: %PRETTY_NAME% Connection
    kind: "Secret" # Authorization type. Either Secret or OAuth
    is_subdomain: true # Will show subdomain field during connection creation
    external_system_name: EXTERNAL_SYSTEM_NAME # Name of the external system, for example: Salesforce, Asana, etc.
    secret_config:
      secret_transform: ".token" # jq secret tranformation function
      fields:
        - id: token
          name: Token # Name of the secret field during connection creation
          description: Example API token
      token_verification:
        url: https://app.devrev.ai/favicon.ico # Airdrop service will call the url with the token to verify its validity.
        method: GET

imports:
  - slug: %PROJECT_NAME%
    display_name: %PRETTY_NAME%
    description: %PRETTY_NAME% description
    extractor_function: extraction
    loader_function: loading
    allowed_connection_types:
      - pat-connection

hooks:
  - type: activate
    function: install_initial_domain_mapping
